### ISSUE TITLE
A clarification: YUKA parenting

### ISSUE THREAD

**Issue by arcman7** [eldinor/yuka-babylonjs-ts-starter#2]
> try to avoid parented TransformNodes with YUKA. YUKA will place your object in world space. Use YUKA's parenting instead.

What YUKA parenting system are you referring to?  I searched through the code at https://github.com/Mugen87/yuka and I couldn't find any references to a parenting system other than that used with the Node class, unrelated to any sort of positioning system.

**Comment by RolandCsibrei** [comment]
Parenting `GameEntity` objects as seen here for example:

https://github.com/eldinor/yuka-babylonjs-examples/blob/f8d9f36fe181dc5f3ef4c2746dbe39ea8d884e37/examples/js/playground/hideAndSeek/src/Player.js#L28

**Comment by arcman7** [comment]
Oh nice! Thanks for the quick reply!
```
   this.headContainer = new GameEntity()
    this.add(this.headContainer)
```

So this actually affects the positioning of child entities; positioning the parent and rotating the parent affects the children entities position and rotation attributes in world space?

**Comment by RolandCsibrei** [comment]
You're welcome! Yes, it definitely should behave like parenting in BJS.
